name: Build
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: mskelton/setup-pnpm@v1
        with:
          node-version: "18.x"
          pnpm-version: 8
      - name: Lint
        run: pnpm lint:ci
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: mskelton/eslint-annotate-action@glob-testing
        with:
          only-pr-files: false
          markdown-report-on-step-summary: true
          report-json: |
            apps/*/eslint-report.json
            packages/*/eslint-report.json
  release:
    strategy:
      matrix:
        service:
          - app
          - foo
    if: startsWith(github.event.head_commit.message, format('Bumped {0} version to ', matrix.service)
    name: Build and Push ${{ matrix.service }} Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Read version
        id: version
        run: |
          filename="./apps/${{ matrix.service }}/version"
          echo "version=$(cat $filename | tr '\n' ' ' | xargs)"
          echo "version=$(cat $filename | tr '\n' ' ' | xargs)" >> "$GITHUB_OUTPUT"
