name: Build
on:
  push:
  workflow_dispatch:
jobs:
  node_test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
        with:
          node-version: '18.x'
          pnpm-version: 8
      - name: Lint
        run: pnpm --filter='*' lint:ci
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: mskelton/eslint-annotate-action@glob-testing
        with:
          report-json: |
            apps/*/eslint-report.json
            packages/*/eslint-report.json
