name: "Deploy"
on: push
jobs:
  deploy:
    strategy:
      matrix:
        app:
          - uw-portal
          - outlook-plugin
        include:
          - app: mt-portal
            dir: deprecated-apps/management-tools
    name: Deploy ${{ matrix.app }} to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: |
          echo "./${{ matrix.dir || format('apps/{0}', matrix.app) }}/Dockerfile"
        shell: bash
