on: pull_request
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/changelog-reminder-action@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
