on: pull_request
name: Changelog Reminder
jobs:
  remind:
    if: false
    name: Changelog Reminder
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/changelog-reminder-action@v3
  e2e:
    name: End-to-end Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: mskelton/setup-yarn@v3
        with:
          node-version: "20.x"
      - name: End-to-end Tests
        run: yarn test:e2e
      - name: Playwright report comment
        if: ${{ always() && github.event_name != 'merge_group' }}
        uses: daun/playwright-report-summary@v3.5.2
        with:
          report-file: "test-results/playwright-json-report.json"
          report-url: https://example.com
          comment-title: "Playwright test results"
          test-command: "yarn test:e2e"
          job-summary: true
