name: Manual Release
on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to release"
        required: true
        default: app-1
        type: choice
        options:
          - app-1
          - app-2
      releaseType:
        description: "Release Type"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  create-release:
    name: Create a new release for ${{ inputs.service }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Release Context
        id: context
        run: |
          echo "PACKAGE_JSON_DIR=apps/${{ inputs.service }}" >> "$GITHUB_OUTPUT"
          echo "VERSION_FILES=apps/${{ inputs.service }}/version" >> "$GITHUB_OUTPUT"

          path="./config/release/${{ inputs.service }}.json"
          if [[ -f "$path" ]]; then
            for s in $(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' "$path"); do
              echo "$s" >> "$GITHUB_OUTPUT"
            done
          fi
      - name: Run action
        uses: ./.github/actions/logger
        with:
          package_json_dir: ${{ steps.context.outputs.PACKAGE_JSON_DIR }}
          version_files: ${{ steps.context.outputs.VERSION_FILES }}
