name: Manual Release
on:
  push:
    branches: ["release/**"]
jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'Bumped ') && contains(github.event.head_commit.message, ' version to ')
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Release Context
        id: context
        run: |
          service="$(echo '${GITHUB_REF##*/}' | sed -E 's/release\/([^\/]+)\/.*/\1/')"
          filename="./apps/$service/version"

          echo "$service"
          echo "version=$(cat $filename | tr '\n' ' ' | xargs)"
