name: Slash Commands
on:
  issue_comment:
    types: [created]
jobs:
  slash-commands:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/')
    steps:
      - name: Stringify github.event
        uses: actions/github-script@v6
        with:
          script: |
            const event = JSON.stringify(context.payload, null, 2);
            console.log(event);
            return event;
          result-encoding: string
        id: stringify-event

      - name: Output Stringified Event
        run: echo "${{ steps.stringify-event.outputs.result }}"
